### PR TITLE
Semver support

### PR DESCRIPTION
**Pull request by logicalparadox**
Added semver support using [node-semver](https://github.com/isaacs/node-semver). 

Got'cha's:
- As not all assets listed use x.x.x version notation, if a semver comparison comes up empty, it will assume a literal version number and attempt to download at the most recent url using that version number.
- Most recent url is grabbed from index 0 in the array of versions for a given asset.

The following work:

```
$ asset install move.js@'>0.0.2'
// installs move.js@0.0.3

$ asset install move.js@0.0.x
// installs move.js@0.0.3
```

Dependancies can also use semver notation.

Let me know if you have any questions/suggestions.

### CODE REVIEW

**Comment by tj** [comment]
awesome :D with all the array madness, it's probably time that we come up with some kind of repo for these. I want to say gists, because then it's easily managed by the community, but at the same time that could get ugly

**Comment by logicalparadox** [comment]
Array madness is right :P The alternative, which may be better depending on how we proceed, is to just list version numbers that are available. Set that aside for a moment though.

Gists could get a little out of hand. I still think the current model (fork/pull request) is best provided we drop the single repo file for a more segmented approach to assets. Homebrew uses formula, for example. But then again, currently you would be managing those pull requests so that is up to you.

Let me know your thoughts, but I will start there for now.

**Comment by tj** [comment]
yeah, the issue with that is when projects evolve and gain deps etc it'll be pretty messy. the fork thing is pretty annoying, even for myself to release every time there's new data. I can set up a simple registry on my linode. I was thinking something easy/quick would be to allow anyone to manipulate the registry but only a few of us moderate it and just ok changes made

**Comment by logicalparadox** [comment]
Are you thinking more of command line like npm or something web based?

Let me know how I can help.

**Comment by tj** [comment]
something web would be better i think. less crap. this way they can just authenticate via twitter, change any of the packages but we would have to just take a quick look to make sure they're not just defacing packages

**Comment by logicalparadox** [comment]
How about authentication via github? If you own the package you can register it and modify its details. If so, its locked from public editing. I realize this wouldn't cover all packages but it would handle a considerable amount of oversight.

**Comment by tj** [comment]
i think that's the thing though, the owners of these packages might not care to edit these things, so I think it's something the community needs to take care of, we just need an easier way of doing it, and an easier way to update (no update at all :D) to expose new packages / changes.

**Pull request closed without merging**
